const quotes = [
    "The only lasting beauty is the beauty of the heart.",
    "The shared joy is a double joy; a shared sorrow is half a sorrow.",
    "He who has a why to live can bear almost any how.",
    "Life is not a problem to be solved, but a reality to be experienced.",
    "The only true wisdom is in knowing you know nothing.",
    "In the middle of difficulty lies opportunity.",
    "The purpose of our lives is to be happy.",
    "Life is what happens when you're busy making other plans.",
    "Get busy living or get busy dying.",
    "You only live once, but if you do it right, once is enough.",
    "Many of life's failures are people who did not realize how close they were to success when they gave up.",
    "If you want to live a happy life, tie it to a goal, not to people or things.",
    "Never let the fear of striking out keep you from playing the game.",
    "Money and success don't change people; they merely amplify what is already there.",
    "Your time is limited, so don't waste it living someone else's life.",
    "Not how long, but how well you have lived is the main thing.",
    "If life were predictable it would cease to be life, and be without flavor.",
    "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.",
    "In order to write about life first you must live it.",
    "The big lesson in life, baby, is never be scared of anyone or anything.",
    "Sing like no one's listening, love like you've never been hurt, dance like nobody's watching, and live like it's heaven on earth.",
    "Curiosity about life in all of its aspects, I think, still is the secret of great creative people.",
    "Life is not a spectator sport. If you're going to spend your whole life in the grandstand, you're going to waste your life.",
    "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    "Everything you've ever wanted is on the other side of fear.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "It is during our darkest moments that we must focus to see the light.",
    "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    "Be yourself; everyone else is already taken.",
    "I have not failed. I've just found 10,000 ways that won't work.",
    "A room without books is like a body without a soul.",
    "You must be the change you wish to see in the world.",
    "If you tell the truth, you don't have to remember anything.",
    "Friendship is born at that moment when one person says to another: 'What! You too? I thought I was the only one.'",
    "No one can make you feel inferior without your consent.",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
    "A feast of words is a joyful thing, but a silence shared is a sacred thing.",
    "The only way to have a friend is to be one.",
    "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.",
    "Do what you can, with what you have, where you are.",
    "The only thing we have to fear is fear itself.",
    "Whether you think you can or you think you can't, you're right.",
    "Act as if what you do makes a difference. It does.",
    "Success usually comes to those who are too busy to be looking for it.",
    "The best way to predict the future is to create it.",
    "You miss 100% of the shots you don't take.",
    "Strive not to be a success, but rather to be of value.",
    "I attribute my success to this: I never gave or took any excuse.",
    "We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.",
    "The question isn't who is going to let me; it's who is going to stop me.",
    "Everything has beauty, but not everyone sees it.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Believe you can and you're halfway there.",
    "Plant your own garden and decorate your own soul, instead of waiting for someone to bring you flowers.",
    "Too many of us are not living our dreams because we are living our fears.",
    "I would rather die of passion than of boredom.",
    "Dream big and dare to fail.",
    "What you do speaks so loudly that I cannot hear what you say.",
    "Tough times never last, but tough people do.",
    "Keep your face always toward the sunshine, and shadows will fall behind you.",
    "It always seems impossible until it's done.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "We may encounter many defeats but we must not be defeated.",
    "The secret of getting ahead is getting started.",
    "It is never too late to be what you might have been.",
    "You do not find a happy life. You make it.",
    "Happiness is not something ready-made. It comes from your own actions.",
    "The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.",
    "To love and be loved is to feel the sun from both sides.",
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Do not watch the clock; do what it does. Keep going.",
    "You are never too old to set another goal or to dream a new dream.",
    "There is no charm equal to tenderness of heart.",
    "No act of kindness, no matter how small, is ever wasted.",
    "If you cannot do great things, do small things in a great way.",
    "The journey of a thousand miles begins with one step.",
    "You must do the things you think you cannot do.",
    "Do one thing every day that scares you.",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    "The only person you are destined to become is the person you decide to be.",
    "Go confidently in the direction of your dreams. Live the life you have imagined.",
    "Change your thoughts and you change your world.",
    "Happiness is when what you think, what you say, and what you do are in harmony.",
    "An unexamined life is not worth living.",
    "All our dreams can come true, if we have the courage to pursue them.",
    "The mind is everything. What you think you become.",
    "The best revenge is massive success.",
    "I have decided to stick with love. Hate is too great a burden to bear.",
    "Life expands or contracts in proportion to one's courage.",
    "The display of courage is the ultimate path to inner peace.",
    "Definiteness of purpose is the starting point of all achievement.",
    "Everything is hard before it is easy.",
    "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.",
    "The measure of intelligence is the ability to change.",
    "Be a voice, not an echo.",
    "The true sign of intelligence is not knowledge but imagination.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "What we achieve inwardly will change outer reality.",
    "Simplicity is the ultimate sophistication."
  ];


const quote_button = document.getElementById("btn");
const q = document.getElementById("allQ");

quote_button.addEventListener('click',()=>{
    const index = Math.floor(Math.random()*100);// 0 to 100 
    q.textContent = quotes[index];
})